### ISSUE TITLE
feat: Implement NUT-03: Swap Tokens

### ISSUE THREAD

**Issue by AbdelStark** [keep-starknet-strange/cashubrew#4]
# Implement NUT-03: Swap Tokens

## Issue Description

We need to implement the swap operation as described in NUT-03 of the Cashu protocol. This operation is crucial for the Cashu system, allowing users to split tokens, prepare for sending, and receive tokens securely.

## Objectives

1. Implement the swap endpoint in the Gakimint mint.
2. Update the wallet CLI to support swap operations for sending and receiving tokens.
3. Ensure the implementation follows the Cashu protocol specifications.

## Tasks

- [ ] Implement the swap endpoint in the mint:
  - [ ] Create a new route `/v1/swap` in the `MintController`.
  - [ ] Implement the swap logic in the `Mint` module.
  - [ ] Validate input proofs and output blinded messages.
  - [ ] Invalidate input proofs and generate new blind signatures.

- [ ] Update the wallet CLI:
  - [ ] Implement a function to prepare inputs and outputs for a swap operation.
  - [ ] Add a command to perform a swap operation (e.g., `swap` or `prepare_send`).
  - [ ] Implement logic to use swap for receiving tokens.

- [ ] Implement security measures:
  - [ ] Ensure the sum of input amounts equals the sum of output amounts.
  - [ ] Verify that input proofs are valid and not already spent.
  - [ ] Implement proper error handling for various scenarios.

- [ ] Privacy enhancements:
  - [ ] Implement sorting of requested outputs by amount in ascending order to preserve privacy.

- [ ] Testing:
  - [ ] Write unit tests for the swap functionality in the mint.
  - [ ] Create integration tests for the swap operation.
  - [ ] Test various scenarios: splitting tokens, preparing to send, receiving tokens.

- [ ] Documentation:
  - [ ] Update API documentation to include the new swap endpoint.
  - [ ] Add examples of how to use the swap operation in the wallet CLI documentation.

### Request

```http
POST /v1/swap
```

Request body (`PostSwapRequest`):
```json
{
  "inputs": [Proof],
  "outputs": [BlindedMessage]
}
```

### Response

Response body (`PostSwapResponse`):
```json
{
  "signatures": [BlindSignature]
}
```

## Considerations

- Performance: The swap operation should be efficient, especially when dealing with multiple inputs and outputs.
- Privacy: Ensure that the implementation doesn't leak unnecessary information about the nature of the swap (e.g., whether it's for sending or receiving).
- Error Handling: Implement robust error handling for various scenarios (e.g., invalid inputs, double-spending attempts).

## Acceptance Criteria

- The mint can successfully process swap requests, invalidating input proofs and generating new blind signatures.
- The wallet CLI can prepare and execute swap operations for both sending and receiving tokens.
- All edge cases are handled properly (e.g., attempts to spend already spent proofs, mismatched input/output amounts).
- The implementation passes all unit and integration tests.
- The API documentation is updated to reflect the new swap endpoint.

## Resources

- [NUT-03 Specification](https://github.com/cashubtc/nuts/blob/main/03.md)
- [NUT-00 Specification](https://github.com/cashubtc/nuts/blob/main/00.md) (for BDHKE details)

## Estimated Effort

Medium: This is a core feature of the Cashu protocol and requires careful implementation and testing.

## Priority

High: The swap operation is fundamental to the functioning of the Cashu system.
